### ISSUE TITLE
ESGF parameter update fails

### ISSUE THREAD

**Issue by tobstac** [Prodiguer/synda#106]
After running `synda update`, I get an error message concerning the ESGF parameter retrieval
`File "~/Synda/sdt/lib/sd/sddao.py", line 26, in add_parameter_value`
`conn.execute("insert into param (name,value) values (?,?)",(name,value))`
`IntegrityError: UNIQUE constraint failed: param.name, param.value`
Looking into this, I found that one key - value pair ('grid', 'regular 1/2? lat-lon grid' ) are retrieved twice causing this error. I cannot say whether this is related to synda or to the dkrz node I am using.

It is possible to walk around this problem when putting the the `conn.execute` within a try statements like
```python
try:
    conn.execute("insert into param (name,value) values (?,?)",(name,value))
except:
    commit=False
```
Does this already qualify as a fix or would it cause problems somewhere else?

**Comment by AtefBN** [comment]
Hi @tobstac this is actually not a Synda issue. We have (thanks to Synda) found out there was a few badly ingested data published on Solr which led to a duplicate facet (regular 1/2? lat-lon grid). When Synda tries to update its facet list from the search api the two values are returned but cannot be persisted to the db because of the unicity constraint. 
That being said, I'm currently working on a fix to make the fail more graceful and more importantly more verbose. Also note that @glevava from IPSL already informed datanode managers about the issue and provided a script to fix the Solr data. 
In the meantime if you wish to alter the synda source file to avoid the crash I have changed sddao.py here to prevent the crash: https://gist.github.com/AtefBN/d2f55c26f5958a5be7653e81ef630ea3 
Cheers.

**Comment by tobstac** [comment]
Thanks a lot for the clarification and the temporary fix.
