### ISSUE TITLE
'synda search' return incorrect result

### ISSUE THREAD

**Issue by jripsl** [Prodiguer/synda#34]
'synda search' return incorrect result

```
$ synda search CORDEX
new    cmip5.output2.IPSL.IPSL-CM5B-LR.piControl.yr.ocnBgchem.Oyr.r1i1p1.v20120430
new    cmip5.output1.IPSL.IPSL-CM5B-LR.rcp45.yr.ocnBgchem.Oyr.r1i1p1.v20120430
new    cmip5.output1.IPSL.IPSL-CM5A-LR.decadal1995.yr.ocnBgchem.Oyr.r1i1p1.v20120430
```

Corresponding query is

http://esgf-data.dkrz.de/esg-search/search?fields=instance_id,id,type,data_node,variable&project=CMIP5&project=CORDEX&limit=100&distrib=true&type=Dataset&ensemble=r1i1p1&format=application%2Fsolr%2Bxml&offset=0

**Comment by jripsl** [comment]
This problem occurs when project is set in default configuration file.

```
$ grep project /etc/synda/sdt/default/default.txt
project=CMIP5
```

**Comment by jripsl** [comment]
Fixed.

Now project set in default.txt is removed if project is set in CLI or in selection file.

**Comment by papplegate** [comment]
Perhaps related: `synda search` appears to return a tiny fraction of the files available from the Earth System Grid.  

```
$ synda search project=CMIP5 | wc -l
100
```

That is, synda says that the entire CMIP5 archive contains just 100 files.  I think the correct number of files should be in the tens of thousands.  I've had similar problems with `synda get` returning fewer files than I obtain from the Earth System Grid Web interface.  

To my knowledge, I haven't changed any relevant settings since installing synda.  

Thanks for your help!  

Patrick

**Comment by jripsl** [comment]
Reasons for this behaviour are:

A) to prevent flooding the user with thousands of files when no filter (facet) is set.
B) to improve response time (i.e. "synda search" starts displaying results only when all data have been retrieved from the server).

You can add limit=N to increase the number of result

e.g. 

    synda search project=CMIP5 limit=5000

I will add a documented option '-l/--limit' to `synda search` to make this behaviour more explicit.

**Comment by jripsl** [comment]
Done ('--limit' option added in 3.5)
