### ISSUE TITLE
running synda daemons on the same host with different configs

### ISSUE THREAD

**Issue by cehbrecht** [Prodiguer/synda#68]
We wanted to use synda to replicate data for two different projects. We have one synda installation on a single host ... but we have learned that we can't easily start two synda daemons with a different configuration for each project. Our workaround was to use a synda docker container to run the second instance, see also #67.

I would have expected to start a second instance may be in this way:

     $ synda daemon -c other_project.cfg start

**Comment by SebastienDenvil** [comment]
It depends on what is meant by configuration and project. Up to now we have been able to accommodate our needs by having multiple selection file.
http://prodiguer.github.io/synda/sdt/selection_file_param_ref.html

Can you elaborate on the use case?

**Comment by cehbrecht** [comment]
the concrete use case: 

we have a synda running to replicate esgf data in the cmip6 test-federation with post-processing (auto-publish?) configured. Now, I needed to run a synda to replicate for our Copernicus instance, with synda running on the same host. Configs are different and in Copernicus we don't use the post-processing. 

We asked how to start synda for the Copernicus instance on the same host ... but it sounded that it was not so easy to do :) My workaround was to use synda running in a docker container for Copernicus.

**Comment by SebastienDenvil** [comment]
The way we use it is that we have one synda instance per host that will do the job for multiple purpose.

Which is some sort of equivalent to have one synda per container per purpose.

**Comment by glevava** [comment]
synda post-processing is able to manage several pipelines on the same host. The difficulty is to manager the "local_path" of your different replicas especially in the case of same projects (i.e., CMIP5 in your case).
Download files under different "data_path" folder is not possible because it's parameter is uniq for the synda instance (in sdt.conf).
A workaround is possible using the selection file parameter "local_path_template" but error-prone.
I think we reach here some synda limits and we recommend to use different synda hosts in your case.
