### ISSUE TITLE
Transfer failures

### ISSUE THREAD

**Issue by meteorologist15** [Prodiguer/synda#97]
This transfer doesn't work.

>>synda search cmip5 o2 Omon MRI-ESM1 rcp85
new  cmip5.output1.MRI.MRI-ESM1.rcp85.mon.ocnBgchem.Omon.r1i1p1.v20140210
>>synda get cmip5.output1.MRI.MRI-ESM1.rcp85.mon.ocnBgchem.Omon.r1i1p1.v20140210
5 file(s) will be downloaded for a total size of 3.0 GB.
Transfer failed with error 1 (did you subscribe to the required role/group ? (e.g. cmip5_research, cordex_research))
Download failed (http://esgf-data1.diasjp.net/thredds/fileServer/esg_dataroot/cmip5/output1/MRI/MRI-ESM1/rcp85/mon/ocnBgchem/Omon/r1i1p1/v20140210/o2/o2_Omon_MRI-ESM1_rcp85_r1i1p1_200601-210012.nc)

However, this works fine (from the example section for "synda get":
>>synda get cmip5.output1.CCCma.CanCM4.decadal1972.fx.atmos.fx.r0i0p0.v20120601

Any ideas what might be causing these transfer failures? My ESGF credentials are correct.

**Comment by painter1** [comment]
I don't know, but when I see something like that I re-run myproxy-logon with the -b option, because often some server's credentials have changed.  Then I try to get the file it with wget; there are usually more error messages.  Admittedly, it can be tricky to come up with the right wget options.

DIAS is a very slow data node.   I wouldn't be surprised if it were temporarily down, and a retry would work.

**Comment by YanchunHe** [comment]
`synda certificate renew` or/and `synda token -p globus renew` fix this problem at my side.

**Comment by pjournou-ipsl** [comment]
CORDEX data may require specific credentials. Contact the data provider.
